version: '3'

x-common-variables: &common-variables
  MYSQL_DATABASE: 'fullstack'
  MYSQL_USER: 'fullstack_user'
  MYSQL_PASSWORD: 'secret-pw'

services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    expose:
      - "3306"
    ports:
      - 127.0.0.1:3306:3306
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: 'root-secret-pw'
    networks:
      - backend

  backend:
    depends_on:
      - db
    container_name: studentsystem
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        maven_artifactId: studentsystem
        maven_version: 0.0.1-SNAPSHOT
    expose:
      - "8080"
    ports:
      - 127.0.0.1:8080:8080
    environment:
      <<: *common-variables
      MYSQL_HOST: 'db'
      MYSQL_PORT: '3306'
    networks:
      - backend
      - frontend

  frontend:
    depends_on:
      - backend
    container_name: studentfrontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    ports:
      - 127.0.0.1:80:80
    networks:
      - backend
      - frontend

  lb:
    depends_on:
      - frontend
    container_name: lb-nginx
    restart: always
    build:
      context: ./lb
      dockerfile: Dockerfile
    ports:
      - "3080:80"
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
    name: frontend
  backend:
    driver: bridge
    name: backend
