version: '3'
services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: 'fullstack'
      MYSQL_ROOT_PASSWORD: 'my-secret-pw'
    ports:
      - 3306:3306
  backend:
    container_name: studentsystem
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        maven_artifactId: studentsystem
        maven_version: 0.0.1-SNAPSHOT
    expose:
      - "8080"
    environment:
      - JAVA_OPTS=-server -Xms512M -Xmx1024M
    depends_on:
      - db
    ports:
      - "8080:8080"
  frontend:
    container_name: studentfrontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - 3000:3000
